### ISSUE TITLE
Swarm Overlay network issues

### ISSUE THREAD

**Issue by AyluinReymaer** [binhex/arch-sabnzbdvpn#15]
Hello,

I found an issue with the image in which if you have a swarm and the container is in an overlay network.

It throws an error stating: `write UDP: Operation not permitted`

I've managed to find a workaround which is at the bottom of the issue.

### Troubleshooting steps:

When a container is in an overlay network, the container is setup with 2 network drives:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.0.1.48  netmask 255.255.255.0  broadcast 10.0.1.255
        ether 02:42:0a:00:01:30  txqueuelen 0  (Ethernet)
        RX packets 15  bytes 630 (630.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.18.0.13  netmask 255.255.0.0  broadcast 172.18.255.255
        ether 02:42:ac:12:00:0d  txqueuelen 0  (Ethernet)
        RX packets 85  bytes 24480 (23.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 60  bytes 8583 (8.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

eth0: overlay network
eth1: gwbridge automatically created by the swarm which is the one that has internet connection

I've checked the supervisord.log and this is the iptables that it is generating and as you can see, it is using the overlay network (eth0) ip range:

```
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT DROP
-A INPUT -s 10.0.1.0/24 -d 10.0.1.0/24 -j ACCEPT
-A INPUT -i eth0 -p udp -m udp --sport 80 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 8090 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --sport 8090 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -i tun0 -j ACCEPT
-A OUTPUT -s 10.0.1.0/24 -d 10.0.1.0/24 -j ACCEPT
-A OUTPUT -o eth0 -p udp -m udp --dport 80 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8080 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --dport 8090 -j ACCEPT
-A OUTPUT -o eth0 -p tcp -m tcp --sport 8090 -j ACCEPT
-A OUTPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
-A OUTPUT -o tun0 -j ACCEPT
```

### Workaround

1- While the container is running (even if it is throwing that write UDP error) connect to it's shell.
2- Copy the file /root/iptable.sh to a volume that you mounted
3- Edit the line in iptable.sh where it says `docker_interface=$(netstat -ie | grep -vE "lo|tun|tap" | sed -n '1!p' | grep -P -o -m 1 '^[^:]+')` to `docker_interface=eth1` (in my case it's eth1 that has internet connection, might be different for others)
4- Mount this modified file as read only to the path /root/iptable.sh

I believe the best solution would be for this script to loop through the interfaces to check which one has internet connection or maybe using an env variable like `DOCKER_BRIDGE_NETWORK=172.18.0.0/16`, check the interface that uses this ip range and set it to the variable `docker_interface` in iptables.sh.

**Comment by AyluinReymaer** [comment]
Just figured out that the solution above is not complete (for me at least).

I am unable to contact my container through the eth0 network which is required for me.

I'll have to learn a little bit more on how to manage iptables and see what I can do to add the eth0 network in the iptables.

**Comment by binhex** [comment]
https://github.com/binhex/arch-delugevpn/issues/163

**Comment by AyluinReymaer** [comment]
Ended up giving up...

Since I can connect to the container through eth1 I'll just use that one.

Didn't exactly want to do it that way because it exposes the container's ports to the host network, but it is not a big enough issue to have to grind my head around it for weeks.

My current setup for future users that have something similar to what I have:

### Docker Compose File
```
version: "3.6"

services:
	sabnzbd_vpn:
        image: "binhex/arch-sabnzbdvpn"
        hostname: sabnzbd_vpn
        container_name: "sabnzbd_vpn"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${DOCKERDIR}/tower/containers/sabnzbd_vpn/data:/data
#            - ${DOCKERDIR}/tower/containers/sabnzbd_vpn/root/start.sh:/root/start.sh:ro
            - ${DOCKERDIR}/tower/containers/sabnzbd_vpn/root/iptable.sh:/root/iptable.sh:ro
#            - ${DOCKERDIR}/tower/containers/sabnzbd_vpn/root/iptable_custom.sh:/root/iptable_custom.sh:ro
            - ${DOCKERDIR}/tower/containers/sabnzbd_vpn/config:/config
            - ${GENERALDIR}/Downloads/SABnzbd - Incomplete:/SABnzbd - Incomplete
            - ${GENERALDIR}/Downloads/SABnzbd - Completed:/SABnzbd - Completed
        ports:
            - "9004:8080"
#            - "9005:8090"
        restart: unless-stopped
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${TZ}
            - VPN_ENABLED=yes
            - VPN_USER=${VPN_USER}
            - VPN_PASS=${VPN_PASS}
            - VPN_PROV=custom
#            - DEBUG=true
#            - VPN_PROTOCOL=tcp
#            - ENABLE_PRIVOXY=yes
            - LAN_NETWORK=192.168.1.0/24
            - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
            - UMASK=002
        cap_add:
            - NET_ADMIN
        networks:
            compose_overlay:
			
networks:
    compose_overlay:
        driver: overlay
```

### iptable.sh content

Change the line: `docker_interface=$(netstat -ie | grep -vE "lo|tun|tap" | sed -n '1!p' | grep -P -o -m 1 '^[^:]+')`

To: `docker_interface=eth1` (use the interface that is being used for the bridge)

This is what is fixing the issue for me.

@binhex Technically, the issue will still be there for others, this is just a workaround. What do you think? Can the issue be closed or should it stay open?
